apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-apache-deployment
  labels:
    app: custom-apache1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: custom-apache1
  template:
    metadata:
      labels:
        app: custom-apache1
    spec:
      containers:
      - name: apache-container
        image: nwudofidelis/custom-apache:v16
        ports:
        - containerPort: 80